site_name: Bootstrap Coding Skills
site_description: Bootstrap your coding skills to get started with a solid foundation.
site_author: Chris Lunsford
site_url: https://cmlccie.github.io/bootstrap/

# Repository information
repo_name: cmlccie/bootstrap
repo_url: https://github.com/cmlccie/bootstrap
edit_uri: edit/main/docs/

# Theme configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
    - content.action.view
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

# Plugins
plugins:
  - search

# Markdown extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

# Navigation
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Git:
      - Overview: git/index.md
      - Interactive Learning: git/interactive-learning.md
      - Staging and Commits: git/staging-commits.md
      - Gitignore: git/gitignore.md
      - Merge Conflicts: git/merge-conflicts.md
      - Quick Reference: git/reference.md
  - Java:
      - Overview: java/index.md
      - Development Environment: java/setup.md
      - Basic Syntax: java/syntax.md
      - Data Structures: java/data-structures.md
      - Idiomatic Java: java/idioms.md
      - Quick Reference: java/reference.md
  - Contributing: contributing.md

# Extra configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cmlccie/bootstrap
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cmlccie
  analytics:
    provider: google
    property: G-XXXXXXXXXX # Replace with your Google Analytics ID
